// AUTO-GENERATED BY scripts/generate-vue-ui-token-entries.cjs
export { default } from './accordion/accordion-trigger.vue'
export { default as AccordionTrigger } from './accordion/accordion-trigger.vue'
