// AUTO-GENERATED BY scripts/generate-vue-ui-token-entries.cjs
export { default } from './alert-dialog/alert-dialog-trigger.vue'
export { default as AlertDialogTrigger } from './alert-dialog/alert-dialog-trigger.vue'
