// AUTO-GENERATED BY scripts/generate-vue-ui-token-entries.cjs
export { default } from './alert-dialog/alert-dialog-action.vue'
export { default as AlertDialogAction } from './alert-dialog/alert-dialog-action.vue'
