// AUTO-GENERATED BY scripts/generate-vue-ui-token-entries.cjs
export { default } from './alert-dialog/alert-dialog-header.vue'
export { default as AlertDialogHeader } from './alert-dialog/alert-dialog-header.vue'
