// AUTO-GENERATED BY scripts/generate-vue-ui-token-entries.cjs
export { default } from './alert-dialog/alert-dialog-footer.vue'
export { default as AlertDialogFooter } from './alert-dialog/alert-dialog-footer.vue'
