// AUTO-GENERATED BY scripts/generate-vue-ui-token-entries.cjs
export { default } from './alert-dialog/alert-dialog-description.vue'
export { default as AlertDialogDescription } from './alert-dialog/alert-dialog-description.vue'
