// AUTO-GENERATED BY scripts/generate-vue-ui-token-entries.cjs
export { default } from './banner/banner-description.vue'
export { default as BannerDescription } from './banner/banner-description.vue'
