// AUTO-GENERATED BY scripts/generate-vue-ui-token-entries.cjs
export { default } from './breadcrumb/breadcrumb-ellipsis.vue'
export { default as BreadcrumbEllipsis } from './breadcrumb/breadcrumb-ellipsis.vue'
