// AUTO-GENERATED BY scripts/generate-vue-ui-token-entries.cjs
export { default } from './breadcrumb/breadcrumb-separator.vue'
export { default as BreadcrumbSeparator } from './breadcrumb/breadcrumb-separator.vue'
