// AUTO-GENERATED BY scripts/generate-vue-ui-token-entries.cjs
export { default } from './collapsible/collapsible-content.vue'
export { default as CollapsibleContent } from './collapsible/collapsible-content.vue'
