// AUTO-GENERATED BY scripts/generate-vue-ui-token-entries.cjs
export { default } from './collapsible/collapsible-trigger.vue'
export { default as CollapsibleTrigger } from './collapsible/collapsible-trigger.vue'
