// AUTO-GENERATED BY scripts/generate-vue-ui-token-entries.cjs
export { default } from './hover-card/hover-card-trigger.vue'
export { default as HoverCardTrigger } from './hover-card/hover-card-trigger.vue'
