export { default } from './pagination/pagination.vue'
export { default as PaginationContent } from './pagination/pagination-content.vue'
export { default as PaginationEllipsis } from './pagination/pagination-ellipsis.vue'
export { default as PaginationFirst } from './pagination/pagination-first.vue'
export { default as PaginationItem } from './pagination/pagination-item.vue'
export { default as PaginationLast } from './pagination/pagination-last.vue'
export { default as PaginationLink } from './pagination/pagination-link.vue'
export { default as PaginationNext } from './pagination/pagination-next.vue'
export { default as PaginationPrevious } from './pagination/pagination-previous.vue'
export { default as Pagination } from './pagination/pagination.vue'
