// AUTO-GENERATED BY scripts/generate-vue-ui-token-entries.cjs
export { default } from './radio-group/radio-group-item.vue'
export { default as RadioGroupItem } from './radio-group/radio-group-item.vue'
