// AUTO-GENERATED BY scripts/generate-vue-ui-token-entries.cjs
export { default } from './stepper/stepper-description.vue'
export { default as StepperDescription } from './stepper/stepper-description.vue'
