// AUTO-GENERATED BY scripts/generate-vue-ui-token-entries.cjs
export { default } from './tabs/tabs.vue'
export { default as TabsContent } from './tabs/tabs-content.vue'
export { default as TabsList } from './tabs/tabs-list.vue'
export { default as TabsTrigger } from './tabs/tabs-trigger.vue'
export { default as Tabs } from './tabs/tabs.vue'
