// AUTO-GENERATED BY scripts/generate-vue-ui-token-entries.cjs
export { default } from './tags-input/tags-input-clear-trigger.vue'
export { default as TagsInputClearTrigger } from './tags-input/tags-input-clear-trigger.vue'
