// AUTO-GENERATED BY scripts/generate-vue-ui-token-entries.cjs
export { default } from './tags-input/tags-input-control.vue'
export { default as TagsInputControl } from './tags-input/tags-input-control.vue'
