// AUTO-GENERATED BY scripts/generate-vue-ui-token-entries.cjs
export { default } from './tags-input/tags-input-input.vue'
export { default as TagsInputInput } from './tags-input/tags-input-input.vue'
