// AUTO-GENERATED BY scripts/generate-vue-ui-token-entries.cjs
export { default } from './timeline/timeline-separator.vue'
export { default as TimelineSeparator } from './timeline/timeline-separator.vue'
